name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          mkdir -p $HOME/ros2_ws/src
          cp -r . $HOME/ros2_ws/src/mypkg/
          
          cd $HOME/ros2_ws/src
          git clone https://github.com/ryu07/person_msgs.git
          
          # ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
          # 【ここが確認ポイント！】
          # srcフォルダの中身を全部表示します
          echo "=== 📂 ディレクトリの中身確認 📂 ==="
          ls -R $HOME/ros2_ws/src
          echo "==================================="
          # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

          cd $HOME/ros2_ws
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y
          colcon build
          source install/setup.bash
          bash -xv src/mypkg/test/test.bash $HOME
